# app/src/test/resources/robolectric.properties

# this line force Robolectric to use the legacy SQLite implementation
# which is more stable and does not depend on native binaries.
sqliteMode=LEGACY
