name: Android CI/CD - develop-comores

on:
  push:
    branches: [ "feature-31756" ]   
  pull_request:
    branches: [ "feature-31756" ]

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 17

    - name: Decode keystore
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > policies_comores.jks

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build release APK
      run: ./gradlew assembleComoresDevRelease
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: policies-release-apk
        path: app/build/outputs/apk/release/app-release.apk
