name: CI

on:
  push:
    branches:
      - '*'
#    tags:
#      - '!v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Environment info
        run: |
          gradle --version

      - name: build
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Environment info
        run: |
          gradle --version

      - uses: actions/upload-artifact@v2
        with:
          name: openimis-policies-apk-${{github.run_number}}-${{github.sha}}
          path: ./app/build/outputs/**/*.apk

      - name: build
        run: |
          ./gradlew bundleDebug --stacktrace

      - name: Environment info
        run: |
          gradle --version

      - uses: actions/upload-artifact@v2
        with:
          name: openimis-policies-aab-${{github.run_number}}-${{github.sha}}
          path: ./app/build/outputs/**/*.aab


