name: CI

on:
  push:
    branches:
      - 'develop-comores'
#    tags:
#      - '!v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Environment info
        run: |
          gradle --version

      - name: build
        run: |
          ./gradlew assemblecomoresDevDebug --stacktrace

      - name: Environment info
        run: |
          gradle --version

      - uses: actions/upload-artifact@v4
        with:
          name: policies-comores-apk-${{github.run_number}}.apk
          path: ./app/build/outputs/**/*.apk

      - name: build
        run: |
          ./gradlew bundlecomoresDevDebug --stacktrace

      - name: Environment info
        run: |
          gradle --version

      - uses: actions/upload-artifact@v4
        with:
          name: policies-comores-aab-${{github.run_number}}.aab
          path: ./app/build/outputs/**/*.aab
